### ISSUE TITLE
Slack configuration

### ISSUE THREAD

**Issue by tbobm** [particuleio/terraform-scaleway-database#2]
Hi @ArchiFleKs could you please setup the SLACK-related secrets ? 🙏

I don't think I have them at hands, could be nice to have the Workflow statuses in a channel

I think the GitHub bot can be configured, I can probably handle this one by myself :)

- [x] Set the SLACK_TOKEN secret
- [x] Set the SLACK_CHANNEL secret
- [x] Enable the GitHub Slack Bot

**Comment by ArchiFleKs** [comment]
@tbobm slack token is an organization secret so it should be used out of the box. You just need to set the slack channel
