### ISSUE TITLE
Scaleway requires at least 1 digit for users password

### ISSUE THREAD

**Issue by anisf** [particuleio/terraform-scaleway-database#27]
│ Error: scaleway-sdk-go: invalid argument(s): password does not respect constraint, must contain at least 1 digits
│
│   with module.database.scaleway_rdb_user.this["xxx-user"],
│   on .terraform/modules/database/auth.tf line 8, in resource "scaleway_rdb_user" "this":

**Comment by ArchiFleKs** [comment]
fixed in #28
